title:            YUPRA
tagline:          'Summer REU 2024'
url:              https://jbirky.github.io/yupra

author:
  name:           'Jessica Birky'

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-include-cache
